language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"

script:
  - npm run lint
  - npm test
  - npm run test:cov

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
